### ISSUE TITLE
Add Feature Ignore URL Patterns

### ISSUE THREAD

**Issue by sanji11** [phast184/link-checker-tool#10]
Hi, I would like to add a feature where user can include a file with list of URL that they want to ignore while testing your tool. Lemme know what do you think? 😃

**Comment by sanji11** [comment]
### Update
I implemented the feature 🥳 

As you can see in the  following picture, `-f` reports all the URLs where if you include `-i` option, it ignores URL that mentioned in ignore-urls.txt.

![image](https://user-images.githubusercontent.com/64912621/96286837-01462600-0faf-11eb-915b-d7c132c42919.png)


Here is the fork repo link: https://github.com/sanji11/link-checker-tool
The branch is :  issue-10

Lemme know  your review 😃 

Side note: While working on your tool, I found several bugs. Some of them I fixed, some I just left alone. I will make new issues to tell you in more details.

**Comment by phast184** [comment]
Already merged your branch, you can find the commission here ed0c03d
