### ISSUE TITLE
Fixed Path in Package.json

### ISSUE THREAD

**Issue by sanji11** [phast184/link-checker-tool#11]
When I tried to install your tools using `npm link`, it gave me error saying "No such file or directory." I dig deeper and found you provided wrong path in package.json in the `bin` 
```javascript
  "bin": {
    "lct": ".src/link-checker.js"
  },
````
Your link-checker.js file is not in src folder. I changed it in my issue #10.
You can see it here also:
https://github.com/sanji11/link-checker-tool/blob/f43f96e7f3d0d2435823b11646b78ac01f73cfab/package.json#L5-L7

**Comment by phast184** [comment]
Thank you, I have fixed this it.
