### ISSUE TITLE
Error running commands

### ISSUE THREAD

**Issue by matt-ross16** [phast184/link-checker-tool#3]
The commands listed in your instructions were inoperable on my end:

![image](https://user-images.githubusercontent.com/37879416/94306776-91112b00-ff41-11ea-8f45-435df9725f1e.png)

However, I was able to run the program using:

```
node link-checker.js -f index2.html
```

![image](https://user-images.githubusercontent.com/37879416/94306953-ddf50180-ff41-11ea-8208-fde757dbc522.png)

**Comment by phast184** [comment]
Hi, turned out I need to add to my readme. You need to run "npm link" and then you can run "lct -f index2.html" normally. Much appreciation!

**Comment by matt-ross16** [comment]
That worked! Glad I could help work that out
