### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by strawberries73** [phast184/link-checker-tool#7]
The README is not clear.  I followed the instructions and the output was:
![image](https://user-images.githubusercontent.com/39388566/94389554-29fc9d80-011e-11eb-98af-79c179f841a0.png)

**Comment by phast184** [comment]
Hi, thank you for your feedback. Would you be more specific since to run the command argument f is required. For example, if I want to check all urls in a file the command should be "lct -f foo.js".

**Comment by strawberries73** [comment]
When I typed that command, this was the result:
![image](https://user-images.githubusercontent.com/39388566/94390860-e2781080-0121-11eb-9a4c-fddd76a2d0c4.png)

**Comment by phast184** [comment]
yeah I got it, it's a problem for me as well. I've been trying to catch this error. Thank you for your feedback.

**Comment by strawberries73** [comment]
The single check works great but the multiple files check did not work either.
